### ISSUE TITLE
Bug: Fix event API running on the Journal entry form as well. 

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/ParkMark#18]
#### Desired Behavior

> ##### The app should ...

The event API should only run when in the travel planning form, not on the Journal entry form. Also, add loading modal to the events population when editing travel plan. 

#### Actual Behavior

> ##### The app does this instead ...

Currently, the API is running in the background and populating the hidden form element with events when in the Journal form. 

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

When the user adds in a travel date input on the Journal form view. 

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Add if conditional to dateEnd eventListener to only deploy the modal/API if the currentStatus is wishlist.
- [x] Add open modal to the event listener for when user clicks on Editing button. 
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
