### ISSUE TITLE
Issue 6: User receives an alert if travel plans dates have passed. 

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/ParkMark#20]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User receives an alert if travel plans dates have passed. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user clicks into a view from the hero page, they will receive alerts if any of their travel plans are past the current date. They will receive an option to edit their plan or hide the alert. If hidden, the next alert will pop up. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="721" alt="Screen Shot 2024-03-12 at 11 32 01 AM" src="https://github.com/nmotamedi/ParkMark/assets/144378279/e6d0e4a2-eb61-4a35-a74e-76868d1df9f4">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a function that checks if any parks have a dateToVisitStart prior to current date. 
   - [x] Calls alerts if any are passed. 
   - [x] Add event listeners to buttons on Alert.
- [x] Call the function when any of the hero buttons are clicked. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
